import { useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import Seo from '../../components/Seo.jsx';
import CertificationCard from '../../components/CertificationCard.jsx';
import Navbar from '../../components/Navbar.jsx';
import Footer from '../../sections/Footer.jsx';
import { certificationService } from '../../services/certificationService.js';
import { usePreferences } from '../../hooks/usePreferences.jsx';
export default function CategoryCertificationsPage({category,title}){const [items,setItems]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const {language,t}=usePreferences();const id=language==='id';const load=()=>{setLoading(true);setError('');certificationService.byCategory(category).then(setItems).catch((e)=>setError(e.message)).finally(()=>setLoading(false))};useEffect(()=>{load()},[category]);return <><Navbar/><main className="subpage"><Seo title={`${title} Certifications | Muhammad Reza Pahlevi Harahap`} description={`${title} professional certifications by Muhammad Reza Pahlevi Harahap.`}/><Link className="back" to="/">← {t.common.home}</Link><span className="eyebrow">{t.sections.certifications.toUpperCase()}</span><h1>{title}</h1><p className="sub-intro">{id?`Sertifikasi profesional terpilih pada kategori ${title}.`:`Selected professional certifications in ${title}.`}</p>{error?<div className="state">{id?'Data tidak dapat dimuat.':'Unable to load data.'} <button onClick={load}>{t.common.retry}</button></div>:loading?<div className="cert-grid">{[1,2,3].map((x)=><div className="skeleton cert-skeleton" key={x}/>)}</div>:items.length?<div className="cert-grid">{items.map((x)=><CertificationCard item={x} key={x.id}/>)}</div>:<div className="empty-panel">{t.common.empty}</div>}</main><Footer/></>}
